name: 'Setup Project'
description: 'caches and installs dependencies'

inputs: 
  caching:
    description: 'whether to cache dependencies'
    required: false
    default: 'true'

outputs:
  used-cache:
    description: 'whether the cache was used'
    value: 'true'

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    # New format for setting outputs
    # - name: Set output
    #   run: echo "{name}={value}" >> $GITHUB_OUTPUT

    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: |
        echo "{caching}={inputs.caching}" >> $GITHUB_OUTPUT
        npm ci
      shell: bash
