name: 'Setup Project'
description: 'caches and installs dependencies'

inputs: 
  caching:
    description: 'whether to cache dependencies'
    required: true
    default: 'true'

outputs:
  used-cache:
    description: 'whether the cache was used'
    value: ${{ steps.install.outputs.caching }}

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: |
        echo 'set-output caching=${{ inputs.caching }}'
        npm ci
      shell: bash
