name: 'Setup Project'
description: 'Checks out code, caches and installs dependencies'

inputs: 
  node-path:
    description: 'Path for node modules cache'
    required: true
    default: 'node_modules'

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.node-path }}
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
