# Github actions JS custom action to deploy to S3
name: 'Deploy to S3'
description: 'Deploys a static website to S3'

inputs:
  bucket:
    description: 'The name of the bucket to deploy to'
    required: true
  bucket-region:
    description: 'The region of the bucket to deploy to'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder to deploy'
    required: false
    default: 'dist'

outputs:
  url:
    description: 'The URL of the deployed website'

runs:
  using: "node16"
  # pre: 'pre.js'
  main: "main.js"
  # post: "post.js"
