name: Deploy to S3 using Javascript Github Action
on: [push]

jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Custom Action
        uses: ./.github/actions/deploy-to-s3
