name: Deploy to S3 using Javascript Github Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Project
        uses: ./.github/actions/setup
        with:
          caching: 'true'
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  information:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Custom Action
        uses: ./.github/actions/deploy-s3-js
