name: Deploy to S3 using Javascript Github Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Project
        uses: ./.github/actions/setup
        with:
          caching: 'true'
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: dist
      - name: Run Custom Action
        uses: ./.github/actions/deploy-s3-js
        id: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: 'github-actions-js-site'
          bucket-region: 'us-east-1'
          dist-folder: './dist'
      - name: Output Information
        run: |
          echo "Live URL: ${{ steps.deploy.outputs.url }}"
